export enum API_ENDPOINTS {
  CREATE = "/users",
  LIST = "/users",
  ALL_USERS = "/users",
  UPDATE = "/users/:id",
  DELETE = "/users/:id",
  LOGIN = "/login",
  DETAILS = "/users/:id",
  LIST_CHAT = "/chat",
  SINGLE_CHAT = "/chat/:id",
  LIST_ALL_USERS_CHAT = "/chat/",
  CHECK_ACCESS_OR_CREATE = "/chat",
  GET_ALL_CONVERSATION = "/chat/:id",
  GET_LIST_OF_CHATS = "/chat-all",
  CREATE_GROUP_CHAT = "/chat",
  UPDATE_GROUP_CHAT = "/chat/:id",
  CREATE_MESSAGE = "/chat/:chat_id/message",
}
